import Head from 'next/head'

import { Button, Grid, Stack, Typography, CircularProgress } from "@mui/material";
import { useState, useEffect } from 'react';
import { DateTime } from "luxon"
import axios from "axios";

import Schedule from './schedule';

export default function Home() {
  const BASE_URL = 'https://f1-schedule-api-kekredzema-uc.a.run.app'

  const [schedule, setSchedule] = useState([]);
  const [isLoadingSchedule, setLoadingSchedule] = useState(true);

  useEffect(() => {
    async function fetchData() {
      const YEAR = DateTime.now().year;
      const response = await axios.get(`${BASE_URL}/calendar/${YEAR}/year`);
      const { data } = response;
      setSchedule(data);
      setLoadingSchedule(false);
    }

    fetchData().catch(err => console.log(`Error: ${err.message}`));
  }, [isLoadingSchedule])

  return (
    <>
      <Head>
        <title>F1 Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container alignItems="center" direction="column">
        <Typography variant='h2'>F1 Calendar</Typography>

        {isLoadingSchedule && <CircularProgress size="large" />}
        {!isLoadingSchedule && <Schedule schedule={schedule} />}
      </Grid>
    </>
  )
}
